##### Copyright 2019 The TensorFlow Authors.

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Classify structured data with feature columns

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/structured_data/feature_columns">
    <img src="https://www.tensorflow.org/images/tf_logo_32px.png" />
    View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://www.tensorflow.org/images/colab_logo_32px.png" />
    Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />
    View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/structured_data/feature_columns.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

Note: If you are starting a new project to classify structured data, we recommend you use [preprocessing layers](https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers).

This tutorial demonstrates how to classify structured data (e.g. tabular data in a CSV). We will use [Keras](https://www.tensorflow.org/guide/keras) to define the model, and [feature columns](https://www.tensorflow.org/guide/feature_columns) as a bridge to map from columns in a CSV to features used to train the model. This tutorial contains complete code to:

* Load a CSV file using [Pandas](https://pandas.pydata.org/).
* Build an input pipeline to batch and shuffle the rows using [tf.data](https://www.tensorflow.org/guide/datasets).
* Map from columns in the CSV to features used to train the model using feature columns.
* Build, train, and evaluate a model using Keras.

## The Dataset

We will use a simplified version of the PetFinder [dataset](https://www.kaggle.com/c/petfinder-adoption-prediction). There are several thousand rows in the CSV. Each row describes a pet, and each column describes an attribute. We will use this information to predict the speed at which the pet will be adopted.

Following is a description of this dataset. Notice there are both numeric and categorical columns. There is a free text column which we will not use in this tutorial.

Column | Description| Feature Type | Data Type
------------|--------------------|----------------------|-----------------
Type | Type of animal (Dog, Cat) | Categorical | string
Age |  Age of the pet | Numerical | integer
Breed1 | Primary breed of the pet | Categorical | string
Color1 | Color 1 of pet | Categorical | string
Color2 | Color 2 of pet | Categorical | string
MaturitySize | Size at maturity | Categorical | string
FurLength | Fur length | Categorical | string
Vaccinated | Pet has been vaccinated | Categorical | string
Sterilized | Pet has been sterilized | Categorical | string
Health | Health Condition | Categorical | string
Fee | Adoption Fee | Numerical | integer
Description | Profile write-up for this pet | Text | string
PhotoAmt | Total uploaded photos for this pet | Numerical | integer
AdoptionSpeed | Speed of adoption | Classification | integer

## Import TensorFlow and other libraries

In [2]:
!pip install -q sklearn

You should consider upgrading via the '/tmpfs/src/tf_docs_env/bin/python -m pip install --upgrade pip' command.


In [3]:
import numpy as np
import pandas as pd

import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

## Use Pandas to create a dataframe

[Pandas](https://pandas.pydata.org/) is a Python library with many helpful utilities for loading and working with structured data. We will use Pandas to download the dataset from a URL, and load it into a dataframe.

In [4]:
import pathlib

dataset_url = 'http://storage.googleapis.com/download.tensorflow.org/data/petfinder-mini.zip'
csv_file = 'datasets/petfinder-mini/petfinder-mini.csv'

tf.keras.utils.get_file('petfinder_mini.zip', dataset_url,
                        extract=True, cache_dir='.')
dataframe = pd.read_csv(csv_file)

   8192/1668792 [..............................] - ETA: 0s

1671168/1668792 [==============================] - 0s 0us/step


In [5]:
dataframe.head()

Type  Age                Breed1  Gender Color1    Color2 MaturitySize  \
0  Cat    3                 Tabby    Male  Black     White        Small   
1  Cat    1  Domestic Medium Hair    Male  Black     Brown       Medium   
2  Dog    1           Mixed Breed    Male  Brown     White       Medium   
3  Dog    4           Mixed Breed  Female  Black     Brown       Medium   
4  Dog    1           Mixed Breed    Male  Black  No Color       Medium   

  FurLength Vaccinated Sterilized   Health  Fee  \
0     Short         No         No  Healthy  100   
1    Medium   Not Sure   Not Sure  Healthy    0   
2    Medium        Yes         No  Healthy    0   
3     Short        Yes         No  Healthy  150   
4     Short         No         No  Healthy    0   

                                         Description  PhotoAmt  AdoptionSpeed  
0  Nibble is a 3+ month old ball of cuteness. He ...         1              2  
1  I just found it alone yesterday near my apartm...         2              0  
2  Their pregnant mother was dumped by her irresp...         7              3  
3  Good guard dog, very alert, active, obedience ...         8              2  
4  This handsome yet cute boy is up for adoption....         3              2

## Create target variable

The task in the original dataset is to predict the speed at which a pet will be adopted (e.g., in the first week, the first month, the first three months, and so on). Let's simplify this for our tutorial. Here, we will transform this into a binary classification problem, and simply predict whether the pet was adopted, or not.

After modifying the label column, 0 will indicate the pet was not adopted, and 1 will indicate it was.

In [6]:
# In the original dataset "4" indicates the pet was not adopted.
dataframe['target'] = np.where(dataframe['AdoptionSpeed']==4, 0, 1)

# Drop un-used columns.
dataframe = dataframe.drop(columns=['AdoptionSpeed', 'Description'])

## Split the dataframe into train, validation, and test

The dataset we downloaded was a single CSV file. We will split this into train, validation, and test sets.

In [7]:
train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

7383 train examples
1846 validation examples
2308 test examples


## Create an input pipeline using tf.data

Next, we will wrap the dataframes with [tf.data](https://www.tensorflow.org/guide/datasets). This will enable us  to use feature columns as a bridge to map from the columns in the Pandas dataframe to features used to train the model. If we were working with a very large CSV file (so large that it does not fit into memory), we would use tf.data to read it from disk directly. That is not covered in this tutorial.

In [8]:
# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

In [9]:
batch_size = 5 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## Understand the input pipeline

Now that we have created the input pipeline, let's call it to see the format of the data it returns. We have used a small batch size to keep the output readable.

In [10]:
for feature_batch, label_batch in train_ds.take(1):
  print('Every feature:', list(feature_batch.keys()))
  print('A batch of ages:', feature_batch['Age'])
  print('A batch of targets:', label_batch )

Every feature: ['Type', 'Age', 'Breed1', 'Gender', 'Color1', 'Color2', 'MaturitySize', 'FurLength', 'Vaccinated', 'Sterilized', 'Health', 'Fee', 'PhotoAmt']
A batch of ages: tf.Tensor([36 48  3 30 24], shape=(5,), dtype=int64)
A batch of targets: tf.Tensor([1 0 1 0 0], shape=(5,), dtype=int64)


We can see that the dataset returns a dictionary of column names (from the dataframe) that map to column values from rows in the dataframe.

## Demonstrate several types of feature columns
TensorFlow provides many types of feature columns. In this section, we will create several types of feature columns, and demonstrate how they transform a column from the dataframe.

In [11]:
# We will use this batch to demonstrate several types of feature columns
example_batch = next(iter(train_ds))[0]

In [12]:
# A utility method to create a feature column
# and to transform a batch of data
def demo(feature_column):
  feature_layer = layers.DenseFeatures(feature_column)
  print(feature_layer(example_batch).numpy())

### Numeric columns
The output of a feature column becomes the input to the model (using the demo function defined above, we will be able to see exactly how each column from the dataframe is transformed). A [numeric column](https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column) is the simplest type of column. It is used to represent real valued features. When using this column, your model will receive the column value from the dataframe unchanged.

In [13]:
photo_count = feature_column.numeric_column('PhotoAmt')
demo(photo_count)

[[1.]
 [2.]
 [2.]
 [4.]
 [1.]]


In the PetFinder dataset, most columns from the dataframe are categorical.

### Bucketized columns
Often, you don't want to feed a number directly into the model, but instead split its value into different categories based on numerical ranges. Consider raw data that represents a person's age. Instead of representing age as a numeric column, we could split the age into several buckets using a [bucketized column](https://www.tensorflow.org/api_docs/python/tf/feature_column/bucketized_column). Notice the one-hot values below describe which age range each row matches.

In [14]:
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 3, 5])
demo(age_buckets)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### Categorical columns
In this dataset, Type is represented as a string (e.g. 'Dog', or 'Cat'). We cannot feed strings directly to a model. Instead, we must first map them to numeric values. The categorical vocabulary columns provide a way to represent strings as a one-hot vector (much like you have seen above with age buckets). The vocabulary can be passed as a list using [categorical_column_with_vocabulary_list](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_list), or loaded from a file using [categorical_column_with_vocabulary_file](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file).

In [15]:
animal_type = feature_column.categorical_column_with_vocabulary_list(
      'Type', ['Cat', 'Dog'])

animal_type_one_hot = feature_column.indicator_column(animal_type)
demo(animal_type_one_hot)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


### Embedding columns
Suppose instead of having just a few possible strings, we have thousands (or more) values per category. For a number of reasons, as the number of categories grow large, it becomes infeasible to train a neural network using one-hot encodings. We can use an embedding column to overcome this limitation. Instead of representing the data as a one-hot vector of many dimensions, an [embedding column](https://www.tensorflow.org/api_docs/python/tf/feature_column/embedding_column) represents that data as a lower-dimensional, dense vector in which each cell can contain any number, not just 0 or 1. The size of the embedding (8, in the example below) is a parameter that must be tuned.

Key point: using an embedding column is best when a categorical column has many possible values. We are using one here for demonstration purposes, so you have a complete example you can modify for a different dataset in the future.

In [16]:
# Notice the input to the embedding column is the categorical column
# we previously created
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
demo(breed1_embedding)

[[ 0.3324157   0.4197986   0.50347906 -0.49933374  0.01970459 -0.2535548
  -0.01637078  0.37853056]
 [ 0.38036337  0.20561606 -0.15727694  0.00184843 -0.19711411  0.46115682
  -0.05730496 -0.35953665]
 [-0.03274023  0.36311874  0.3822702   0.12975089 -0.6652591   0.5957904
   0.49060807 -0.05435312]
 [ 0.44843388 -0.00815179  0.11813674 -0.22067873  0.03251803 -0.3833288
  -0.45184475  0.5564358 ]
 [ 0.44843388 -0.00815179  0.11813674 -0.22067873  0.03251803 -0.3833288
  -0.45184475  0.5564358 ]]


### Hashed feature columns

Another way to represent a categorical column with a large number of values is to use a [categorical_column_with_hash_bucket](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_hash_bucket). This feature column calculates a hash value of the input, then selects one of the `hash_bucket_size` buckets to encode a string. When using this column, you do not need to provide the vocabulary, and you can choose to make the number of hash_buckets significantly smaller than the number of actual categories to save space.

Key point: An important downside of this technique is that there may be collisions in which different strings are mapped to the same bucket. In practice, this can work well for some datasets regardless.

In [17]:
breed1_hashed = feature_column.categorical_column_with_hash_bucket(
      'Breed1', hash_bucket_size=10)
demo(feature_column.indicator_column(breed1_hashed))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


### Crossed feature columns
Combining features into a single feature, better known as [feature crosses](https://developers.google.com/machine-learning/glossary/#feature_cross), enables a model to learn separate weights for each combination of features. Here, we will create a new feature that is the cross of Age and Type. Note that `crossed_column` does not build the full table of all possible combinations (which could be very large). Instead, it is backed by a `hashed_column`, so you can choose how large the table is.

In [18]:
crossed_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=10)
demo(feature_column.indicator_column(crossed_feature))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


## Choose which columns to use
We have seen how to use several types of feature columns. Now we will use them to train a model. The goal of this tutorial is to show you the complete code (e.g. mechanics) needed to work with feature columns. We have selected a few columns to train our model below arbitrarily.

Key point: If your aim is to build an accurate model, try a larger dataset of your own, and think carefully about which features are the most meaningful to include, and how they should be represented.

In [19]:
feature_columns = []

# numeric cols
for header in ['PhotoAmt', 'Fee', 'Age']:
  feature_columns.append(feature_column.numeric_column(header))

In [20]:
# bucketized cols
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 2, 3, 4, 5])
feature_columns.append(age_buckets)

In [21]:
# indicator_columns
indicator_column_names = ['Type', 'Color1', 'Color2', 'Gender', 'MaturitySize',
                          'FurLength', 'Vaccinated', 'Sterilized', 'Health']
for col_name in indicator_column_names:
  categorical_column = feature_column.categorical_column_with_vocabulary_list(
      col_name, dataframe[col_name].unique())
  indicator_column = feature_column.indicator_column(categorical_column)
  feature_columns.append(indicator_column)

In [22]:
# embedding columns
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
feature_columns.append(breed1_embedding)

In [23]:
# crossed columns
age_type_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=100)
feature_columns.append(feature_column.indicator_column(age_type_feature))

### Create a feature layer
Now that we have defined our feature columns, we will use a [DenseFeatures](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/DenseFeatures) layer to input them to our Keras model.

In [24]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

Earlier, we used a small batch size to demonstrate how feature columns worked. We create a new input pipeline with a larger batch size.

In [25]:
batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## Create, compile, and train the model

In [26]:
model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dropout(.1),
  layers.Dense(1)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(train_ds,
          validation_data=val_ds,
          epochs=10)

Epoch 1/10


Consider rewriting this model with the Functional API.


Consider rewriting this model with the Functional API.


  1/231 [..............................] - ETA: 0s - loss: 1.4813 - accuracy: 0.2812

  8/231 [>.............................] - ETA: 1s - loss: 0.9849 - accuracy: 0.4688

 15/231 [>.............................] - ETA: 1s - loss: 0.9057 - accuracy: 0.5333

 22/231 [=>............................] - ETA: 1s - loss: 0.8459 - accuracy: 0.5739

 29/231 [==>...........................] - ETA: 1s - loss: 0.8605 - accuracy: 0.5991

 36/231 [===>..........................] - ETA: 1s - loss: 0.8527 - accuracy: 0.6137

 43/231 [====>.........................] - ETA: 1s - loss: 0.8352 - accuracy: 0.6301

 50/231 [=====>........................] - ETA: 1s - loss: 0.8324 - accuracy: 0.6300

 57/231 [======>.......................] - ETA: 1s - loss: 0.8188 - accuracy: 0.6299

 64/231 [=======>......................] - ETA: 1s - loss: 0.7988 - accuracy: 0.6436

 71/231 [========>.....................] - ETA: 1s - loss: 0.7821 - accuracy: 0.6488

 78/231 [=========>....................] - ETA: 1s - loss: 0.7738 - accuracy: 0.6454

 85/231 [==========>...................] - ETA: 1s - loss: 0.7608 - accuracy: 0.6438

 92/231 [==========>...................] - ETA: 1s - loss: 0.7520 - accuracy: 0.6454

 99/231 [===========>..................] - ETA: 1s - loss: 0.7396 - accuracy: 0.6521

106/231 [============>.................] - ETA: 0s - loss: 0.7395 - accuracy: 0.6524

113/231 [=============>................] - ETA: 0s - loss: 0.7355 - accuracy: 0.6546

120/231 [==============>...............] - ETA: 0s - loss: 0.7266 - accuracy: 0.6573

127/231 [===============>..............] - ETA: 0s - loss: 0.7277 - accuracy: 0.6602

134/231 [================>.............] - ETA: 0s - loss: 0.7210 - accuracy: 0.6602

141/231 [=================>............] - ETA: 0s - loss: 0.7180 - accuracy: 0.6605

148/231 [==================>...........] - ETA: 0s - loss: 0.7097 - accuracy: 0.6632

155/231 [===================>..........] - ETA: 0s - loss: 0.7106 - accuracy: 0.6605

162/231 [====================>.........] - ETA: 0s - loss: 0.7036 - accuracy: 0.6609

169/231 [====================>.........] - ETA: 0s - loss: 0.6962 - accuracy: 0.6638

176/231 [=====================>........] - ETA: 0s - loss: 0.6910 - accuracy: 0.6658

183/231 [======================>.......] - ETA: 0s - loss: 0.6854 - accuracy: 0.6662

190/231 [=======================>......] - ETA: 0s - loss: 0.6890 - accuracy: 0.6661

197/231 [========================>.....] - ETA: 0s - loss: 0.6841 - accuracy: 0.6677

204/231 [=========================>....] - ETA: 0s - loss: 0.6792 - accuracy: 0.6684

211/231 [==========================>...] - ETA: 0s - loss: 0.6749 - accuracy: 0.6703

218/231 [===========================>..] - ETA: 0s - loss: 0.6696 - accuracy: 0.6730

225/231 [============================>.] - ETA: 0s - loss: 0.6649 - accuracy: 0.6749

Consider rewriting this model with the Functional API.


231/231 [==============================] - 3s 11ms/step - loss: 0.6621 - accuracy: 0.6768 - val_loss: 0.5403 - val_accuracy: 0.6891


Epoch 2/10
  1/231 [..............................] - ETA: 0s - loss: 0.5243 - accuracy: 0.7188

  8/231 [>.............................] - ETA: 1s - loss: 0.5424 - accuracy: 0.6836

 15/231 [>.............................] - ETA: 1s - loss: 0.5633 - accuracy: 0.6938

 23/231 [=>............................] - ETA: 1s - loss: 0.5587 - accuracy: 0.7147

 32/231 [===>..........................] - ETA: 1s - loss: 0.5639 - accuracy: 0.7080

 40/231 [====>.........................] - ETA: 1s - loss: 0.5599 - accuracy: 0.7039

 48/231 [=====>........................] - ETA: 1s - loss: 0.5505 - accuracy: 0.7116

 56/231 [======>.......................] - ETA: 1s - loss: 0.5451 - accuracy: 0.7115

 63/231 [=======>......................] - ETA: 1s - loss: 0.5531 - accuracy: 0.7108

 71/231 [========>.....................] - ETA: 1s - loss: 0.5595 - accuracy: 0.7082

 79/231 [=========>....................] - ETA: 1s - loss: 0.5641 - accuracy: 0.7053

 87/231 [==========>...................] - ETA: 0s - loss: 0.5617 - accuracy: 0.7008

 96/231 [===========>..................] - ETA: 0s - loss: 0.5581 - accuracy: 0.7041

104/231 [============>.................] - ETA: 0s - loss: 0.5608 - accuracy: 0.7067

112/231 [=============>................] - ETA: 0s - loss: 0.5605 - accuracy: 0.7054

120/231 [==============>...............] - ETA: 0s - loss: 0.5652 - accuracy: 0.7036

128/231 [===============>..............] - ETA: 0s - loss: 0.5625 - accuracy: 0.7051

136/231 [================>.............] - ETA: 0s - loss: 0.5614 - accuracy: 0.7045

144/231 [=================>............] - ETA: 0s - loss: 0.5599 - accuracy: 0.7075

152/231 [==================>...........] - ETA: 0s - loss: 0.5619 - accuracy: 0.7060

160/231 [===================>..........] - ETA: 0s - loss: 0.5584 - accuracy: 0.7082

168/231 [====================>.........] - ETA: 0s - loss: 0.5540 - accuracy: 0.7126

176/231 [=====================>........] - ETA: 0s - loss: 0.5537 - accuracy: 0.7131

184/231 [======================>.......] - ETA: 0s - loss: 0.5574 - accuracy: 0.7118

192/231 [=======================>......] - ETA: 0s - loss: 0.5600 - accuracy: 0.7116

200/231 [========================>.....] - ETA: 0s - loss: 0.5577 - accuracy: 0.7134

208/231 [==========================>...] - ETA: 0s - loss: 0.5553 - accuracy: 0.7159

216/231 [===========================>..] - ETA: 0s - loss: 0.5545 - accuracy: 0.7174

224/231 [============================>.] - ETA: 0s - loss: 0.5555 - accuracy: 0.7164

231/231 [==============================] - 2s 8ms/step - loss: 0.5542 - accuracy: 0.7154 - val_loss: 0.5154 - val_accuracy: 0.7210


Epoch 3/10
  1/231 [..............................] - ETA: 0s - loss: 0.6509 - accuracy: 0.6250

  9/231 [>.............................] - ETA: 1s - loss: 0.5540 - accuracy: 0.7257

 17/231 [=>............................] - ETA: 1s - loss: 0.5485 - accuracy: 0.7224

 25/231 [==>...........................] - ETA: 1s - loss: 0.5486 - accuracy: 0.7038

 33/231 [===>..........................] - ETA: 1s - loss: 0.5487 - accuracy: 0.7064

 41/231 [====>.........................] - ETA: 1s - loss: 0.5431 - accuracy: 0.7134

 49/231 [=====>........................] - ETA: 1s - loss: 0.5417 - accuracy: 0.7092

 57/231 [======>.......................] - ETA: 1s - loss: 0.5297 - accuracy: 0.7155

 65/231 [=======>......................] - ETA: 1s - loss: 0.5236 - accuracy: 0.7173

 73/231 [========>.....................] - ETA: 1s - loss: 0.5272 - accuracy: 0.7200

 82/231 [=========>....................] - ETA: 0s - loss: 0.5301 - accuracy: 0.7161

 91/231 [==========>...................] - ETA: 0s - loss: 0.5315 - accuracy: 0.7163

 99/231 [===========>..................] - ETA: 0s - loss: 0.5347 - accuracy: 0.7169

107/231 [============>.................] - ETA: 0s - loss: 0.5326 - accuracy: 0.7182

115/231 [=============>................] - ETA: 0s - loss: 0.5293 - accuracy: 0.7171

123/231 [==============>...............] - ETA: 0s - loss: 0.5268 - accuracy: 0.7165

131/231 [================>.............] - ETA: 0s - loss: 0.5234 - accuracy: 0.7180

139/231 [=================>............] - ETA: 0s - loss: 0.5240 - accuracy: 0.7174

147/231 [==================>...........] - ETA: 0s - loss: 0.5231 - accuracy: 0.7198

155/231 [===================>..........] - ETA: 0s - loss: 0.5252 - accuracy: 0.7198

163/231 [====================>.........] - ETA: 0s - loss: 0.5264 - accuracy: 0.7195

171/231 [=====================>........] - ETA: 0s - loss: 0.5266 - accuracy: 0.7191

179/231 [======================>.......] - ETA: 0s - loss: 0.5254 - accuracy: 0.7200

187/231 [=======================>......] - ETA: 0s - loss: 0.5224 - accuracy: 0.7213

195/231 [========================>.....] - ETA: 0s - loss: 0.5215 - accuracy: 0.7226

203/231 [=========================>....] - ETA: 0s - loss: 0.5214 - accuracy: 0.7234

211/231 [==========================>...] - ETA: 0s - loss: 0.5206 - accuracy: 0.7244

219/231 [===========================>..] - ETA: 0s - loss: 0.5193 - accuracy: 0.7242

227/231 [============================>.] - ETA: 0s - loss: 0.5174 - accuracy: 0.7263

231/231 [==============================] - 2s 8ms/step - loss: 0.5178 - accuracy: 0.7268 - val_loss: 0.4996 - val_accuracy: 0.7411


Epoch 4/10
  1/231 [..............................] - ETA: 0s - loss: 0.6619 - accuracy: 0.6562

  9/231 [>.............................] - ETA: 1s - loss: 0.4834 - accuracy: 0.7396

 17/231 [=>............................] - ETA: 1s - loss: 0.4671 - accuracy: 0.7408

 25/231 [==>...........................] - ETA: 1s - loss: 0.4856 - accuracy: 0.7400

 33/231 [===>..........................] - ETA: 1s - loss: 0.4862 - accuracy: 0.7453

 42/231 [====>.........................] - ETA: 1s - loss: 0.4844 - accuracy: 0.7470

 50/231 [=====>........................] - ETA: 1s - loss: 0.4906 - accuracy: 0.7456

 59/231 [======>.......................] - ETA: 1s - loss: 0.4878 - accuracy: 0.7479

 68/231 [=======>......................] - ETA: 1s - loss: 0.4857 - accuracy: 0.7528

 76/231 [========>.....................] - ETA: 0s - loss: 0.4865 - accuracy: 0.7492

 85/231 [==========>...................] - ETA: 0s - loss: 0.4876 - accuracy: 0.7482

 94/231 [===========>..................] - ETA: 0s - loss: 0.4920 - accuracy: 0.7463

103/231 [============>.................] - ETA: 0s - loss: 0.4933 - accuracy: 0.7424

111/231 [=============>................] - ETA: 0s - loss: 0.4952 - accuracy: 0.7376

119/231 [==============>...............] - ETA: 0s - loss: 0.4958 - accuracy: 0.7377

128/231 [===============>..............] - ETA: 0s - loss: 0.5025 - accuracy: 0.7310

136/231 [================>.............] - ETA: 0s - loss: 0.5023 - accuracy: 0.7302

144/231 [=================>............] - ETA: 0s - loss: 0.5011 - accuracy: 0.7329

152/231 [==================>...........] - ETA: 0s - loss: 0.5022 - accuracy: 0.7315

160/231 [===================>..........] - ETA: 0s - loss: 0.5045 - accuracy: 0.7295

168/231 [====================>.........] - ETA: 0s - loss: 0.5033 - accuracy: 0.7312

176/231 [=====================>........] - ETA: 0s - loss: 0.5027 - accuracy: 0.7322

184/231 [======================>.......] - ETA: 0s - loss: 0.5024 - accuracy: 0.7320

193/231 [========================>.....] - ETA: 0s - loss: 0.5012 - accuracy: 0.7333

202/231 [=========================>....] - ETA: 0s - loss: 0.5016 - accuracy: 0.7321

211/231 [==========================>...] - ETA: 0s - loss: 0.5027 - accuracy: 0.7322

219/231 [===========================>..] - ETA: 0s - loss: 0.5039 - accuracy: 0.7313

227/231 [============================>.] - ETA: 0s - loss: 0.5047 - accuracy: 0.7300

231/231 [==============================] - 2s 8ms/step - loss: 0.5044 - accuracy: 0.7295 - val_loss: 0.4856 - val_accuracy: 0.7449


Epoch 5/10
  1/231 [..............................] - ETA: 0s - loss: 0.4368 - accuracy: 0.7500

  9/231 [>.............................] - ETA: 1s - loss: 0.4685 - accuracy: 0.7778

 18/231 [=>............................] - ETA: 1s - loss: 0.4599 - accuracy: 0.7934

 27/231 [==>...........................] - ETA: 1s - loss: 0.4657 - accuracy: 0.7801

 35/231 [===>..........................] - ETA: 1s - loss: 0.4756 - accuracy: 0.7723

 43/231 [====>.........................] - ETA: 1s - loss: 0.4819 - accuracy: 0.7587

 52/231 [=====>........................] - ETA: 1s - loss: 0.4807 - accuracy: 0.7494

 61/231 [======>.......................] - ETA: 1s - loss: 0.4851 - accuracy: 0.7505

 69/231 [=======>......................] - ETA: 1s - loss: 0.4890 - accuracy: 0.7441

 77/231 [=========>....................] - ETA: 0s - loss: 0.4874 - accuracy: 0.7459

 86/231 [==========>...................] - ETA: 0s - loss: 0.4872 - accuracy: 0.7460

 95/231 [===========>..................] - ETA: 0s - loss: 0.4876 - accuracy: 0.7431

104/231 [============>.................] - ETA: 0s - loss: 0.4893 - accuracy: 0.7416

113/231 [=============>................] - ETA: 0s - loss: 0.4885 - accuracy: 0.7395

122/231 [==============>...............] - ETA: 0s - loss: 0.4845 - accuracy: 0.7439

130/231 [===============>..............] - ETA: 0s - loss: 0.4848 - accuracy: 0.7442

139/231 [=================>............] - ETA: 0s - loss: 0.4873 - accuracy: 0.7408

148/231 [==================>...........] - ETA: 0s - loss: 0.4872 - accuracy: 0.7401

156/231 [===================>..........] - ETA: 0s - loss: 0.4913 - accuracy: 0.7394

164/231 [====================>.........] - ETA: 0s - loss: 0.4913 - accuracy: 0.7405

172/231 [=====================>........] - ETA: 0s - loss: 0.4937 - accuracy: 0.7400

181/231 [======================>.......] - ETA: 0s - loss: 0.4920 - accuracy: 0.7405

189/231 [=======================>......] - ETA: 0s - loss: 0.4926 - accuracy: 0.7399

198/231 [========================>.....] - ETA: 0s - loss: 0.4940 - accuracy: 0.7402

206/231 [=========================>....] - ETA: 0s - loss: 0.4937 - accuracy: 0.7406

215/231 [==========================>...] - ETA: 0s - loss: 0.4941 - accuracy: 0.7408

224/231 [============================>.] - ETA: 0s - loss: 0.4955 - accuracy: 0.7394

231/231 [==============================] - 2s 7ms/step - loss: 0.4956 - accuracy: 0.7398 - val_loss: 0.4814 - val_accuracy: 0.7486


Epoch 6/10
  1/231 [..............................] - ETA: 0s - loss: 0.4523 - accuracy: 0.7188

  9/231 [>.............................] - ETA: 1s - loss: 0.4615 - accuracy: 0.7604

 18/231 [=>............................] - ETA: 1s - loss: 0.4652 - accuracy: 0.7465

 27/231 [==>...........................] - ETA: 1s - loss: 0.4695 - accuracy: 0.7546

 36/231 [===>..........................] - ETA: 1s - loss: 0.4763 - accuracy: 0.7509

 45/231 [====>.........................] - ETA: 1s - loss: 0.4695 - accuracy: 0.7583

 53/231 [=====>........................] - ETA: 1s - loss: 0.4753 - accuracy: 0.7547

 61/231 [======>.......................] - ETA: 1s - loss: 0.4779 - accuracy: 0.7536

 69/231 [=======>......................] - ETA: 0s - loss: 0.4808 - accuracy: 0.7486

 78/231 [=========>....................] - ETA: 0s - loss: 0.4811 - accuracy: 0.7484

 87/231 [==========>...................] - ETA: 0s - loss: 0.4790 - accuracy: 0.7443

 95/231 [===========>..................] - ETA: 0s - loss: 0.4799 - accuracy: 0.7461

104/231 [============>.................] - ETA: 0s - loss: 0.4770 - accuracy: 0.7491

112/231 [=============>................] - ETA: 0s - loss: 0.4852 - accuracy: 0.7422

120/231 [==============>...............] - ETA: 0s - loss: 0.4875 - accuracy: 0.7393

128/231 [===============>..............] - ETA: 0s - loss: 0.4887 - accuracy: 0.7358

137/231 [================>.............] - ETA: 0s - loss: 0.4900 - accuracy: 0.7313

146/231 [=================>............] - ETA: 0s - loss: 0.4880 - accuracy: 0.7333

154/231 [===================>..........] - ETA: 0s - loss: 0.4842 - accuracy: 0.7374

162/231 [====================>.........] - ETA: 0s - loss: 0.4853 - accuracy: 0.7378

170/231 [=====================>........] - ETA: 0s - loss: 0.4852 - accuracy: 0.7388

179/231 [======================>.......] - ETA: 0s - loss: 0.4850 - accuracy: 0.7394

187/231 [=======================>......] - ETA: 0s - loss: 0.4867 - accuracy: 0.7353

196/231 [========================>.....] - ETA: 0s - loss: 0.4870 - accuracy: 0.7364

204/231 [=========================>....] - ETA: 0s - loss: 0.4898 - accuracy: 0.7368

212/231 [==========================>...] - ETA: 0s - loss: 0.4898 - accuracy: 0.7364

220/231 [===========================>..] - ETA: 0s - loss: 0.4902 - accuracy: 0.7358

228/231 [============================>.] - ETA: 0s - loss: 0.4896 - accuracy: 0.7362

231/231 [==============================] - 2s 8ms/step - loss: 0.4894 - accuracy: 0.7363 - val_loss: 0.4875 - val_accuracy: 0.7514


Epoch 7/10
  1/231 [..............................] - ETA: 0s - loss: 0.4579 - accuracy: 0.7500

  9/231 [>.............................] - ETA: 1s - loss: 0.4596 - accuracy: 0.7639

 18/231 [=>............................] - ETA: 1s - loss: 0.4773 - accuracy: 0.7431

 27/231 [==>...........................] - ETA: 1s - loss: 0.4699 - accuracy: 0.7488

 36/231 [===>..........................] - ETA: 1s - loss: 0.4712 - accuracy: 0.7448

 44/231 [====>.........................] - ETA: 1s - loss: 0.4751 - accuracy: 0.7429

 53/231 [=====>........................] - ETA: 1s - loss: 0.4670 - accuracy: 0.7471

 62/231 [=======>......................] - ETA: 1s - loss: 0.4753 - accuracy: 0.7419

 71/231 [========>.....................] - ETA: 0s - loss: 0.4738 - accuracy: 0.7434

 80/231 [=========>....................] - ETA: 0s - loss: 0.4747 - accuracy: 0.7449

 89/231 [==========>...................] - ETA: 0s - loss: 0.4793 - accuracy: 0.7395

 98/231 [===========>..................] - ETA: 0s - loss: 0.4785 - accuracy: 0.7411

107/231 [============>.................] - ETA: 0s - loss: 0.4817 - accuracy: 0.7392

115/231 [=============>................] - ETA: 0s - loss: 0.4814 - accuracy: 0.7394

124/231 [===============>..............] - ETA: 0s - loss: 0.4801 - accuracy: 0.7402

133/231 [================>.............] - ETA: 0s - loss: 0.4785 - accuracy: 0.7404

141/231 [=================>............] - ETA: 0s - loss: 0.4769 - accuracy: 0.7418

149/231 [==================>...........] - ETA: 0s - loss: 0.4777 - accuracy: 0.7414

158/231 [===================>..........] - ETA: 0s - loss: 0.4769 - accuracy: 0.7439

167/231 [====================>.........] - ETA: 0s - loss: 0.4780 - accuracy: 0.7433

176/231 [=====================>........] - ETA: 0s - loss: 0.4799 - accuracy: 0.7422

185/231 [=======================>......] - ETA: 0s - loss: 0.4798 - accuracy: 0.7417

194/231 [========================>.....] - ETA: 0s - loss: 0.4799 - accuracy: 0.7421

203/231 [=========================>....] - ETA: 0s - loss: 0.4814 - accuracy: 0.7418

212/231 [==========================>...] - ETA: 0s - loss: 0.4806 - accuracy: 0.7438

221/231 [===========================>..] - ETA: 0s - loss: 0.4830 - accuracy: 0.7428

230/231 [============================>.] - ETA: 0s - loss: 0.4834 - accuracy: 0.7412

231/231 [==============================] - 2s 7ms/step - loss: 0.4832 - accuracy: 0.7413 - val_loss: 0.4824 - val_accuracy: 0.7443


Epoch 8/10
  1/231 [..............................] - ETA: 0s - loss: 0.6057 - accuracy: 0.5625

  9/231 [>.............................] - ETA: 1s - loss: 0.4970 - accuracy: 0.7361

 18/231 [=>............................] - ETA: 1s - loss: 0.4991 - accuracy: 0.7378

 26/231 [==>...........................] - ETA: 1s - loss: 0.4930 - accuracy: 0.7308

 34/231 [===>..........................] - ETA: 1s - loss: 0.4870 - accuracy: 0.7408

 43/231 [====>.........................] - ETA: 1s - loss: 0.4786 - accuracy: 0.7406

 52/231 [=====>........................] - ETA: 1s - loss: 0.4707 - accuracy: 0.7494

 60/231 [======>.......................] - ETA: 1s - loss: 0.4746 - accuracy: 0.7469

 69/231 [=======>......................] - ETA: 1s - loss: 0.4652 - accuracy: 0.7541

 78/231 [=========>....................] - ETA: 0s - loss: 0.4694 - accuracy: 0.7508

 86/231 [==========>...................] - ETA: 0s - loss: 0.4724 - accuracy: 0.7471

 94/231 [===========>..................] - ETA: 0s - loss: 0.4707 - accuracy: 0.7473

102/231 [============>.................] - ETA: 0s - loss: 0.4731 - accuracy: 0.7460

111/231 [=============>................] - ETA: 0s - loss: 0.4748 - accuracy: 0.7458

119/231 [==============>...............] - ETA: 0s - loss: 0.4827 - accuracy: 0.7395

128/231 [===============>..............] - ETA: 0s - loss: 0.4784 - accuracy: 0.7434

137/231 [================>.............] - ETA: 0s - loss: 0.4786 - accuracy: 0.7425

145/231 [=================>............] - ETA: 0s - loss: 0.4776 - accuracy: 0.7461

153/231 [==================>...........] - ETA: 0s - loss: 0.4775 - accuracy: 0.7469

161/231 [===================>..........] - ETA: 0s - loss: 0.4790 - accuracy: 0.7455

170/231 [=====================>........] - ETA: 0s - loss: 0.4787 - accuracy: 0.7452

179/231 [======================>.......] - ETA: 0s - loss: 0.4767 - accuracy: 0.7467

187/231 [=======================>......] - ETA: 0s - loss: 0.4741 - accuracy: 0.7493

195/231 [========================>.....] - ETA: 0s - loss: 0.4747 - accuracy: 0.7489

204/231 [=========================>....] - ETA: 0s - loss: 0.4752 - accuracy: 0.7492

213/231 [==========================>...] - ETA: 0s - loss: 0.4748 - accuracy: 0.7496

222/231 [===========================>..] - ETA: 0s - loss: 0.4774 - accuracy: 0.7472

230/231 [============================>.] - ETA: 0s - loss: 0.4762 - accuracy: 0.7476

231/231 [==============================] - 2s 7ms/step - loss: 0.4766 - accuracy: 0.7469 - val_loss: 0.4907 - val_accuracy: 0.7134


Epoch 9/10
  1/231 [..............................] - ETA: 0s - loss: 0.5966 - accuracy: 0.5938

  9/231 [>.............................] - ETA: 1s - loss: 0.4599 - accuracy: 0.7326

 17/231 [=>............................] - ETA: 1s - loss: 0.4577 - accuracy: 0.7592

 25/231 [==>...........................] - ETA: 1s - loss: 0.4613 - accuracy: 0.7613

 34/231 [===>..........................] - ETA: 1s - loss: 0.4623 - accuracy: 0.7574

 42/231 [====>.........................] - ETA: 1s - loss: 0.4599 - accuracy: 0.7589

 50/231 [=====>........................] - ETA: 1s - loss: 0.4631 - accuracy: 0.7606

 58/231 [======>.......................] - ETA: 1s - loss: 0.4674 - accuracy: 0.7640

 66/231 [=======>......................] - ETA: 1s - loss: 0.4717 - accuracy: 0.7562

 74/231 [========>.....................] - ETA: 0s - loss: 0.4709 - accuracy: 0.7559

 83/231 [=========>....................] - ETA: 0s - loss: 0.4735 - accuracy: 0.7545

 92/231 [==========>...................] - ETA: 0s - loss: 0.4774 - accuracy: 0.7520

100/231 [===========>..................] - ETA: 0s - loss: 0.4750 - accuracy: 0.7522

109/231 [=============>................] - ETA: 0s - loss: 0.4744 - accuracy: 0.7503

117/231 [==============>...............] - ETA: 0s - loss: 0.4776 - accuracy: 0.7503

126/231 [===============>..............] - ETA: 0s - loss: 0.4730 - accuracy: 0.7515

134/231 [================>.............] - ETA: 0s - loss: 0.4720 - accuracy: 0.7521

142/231 [=================>............] - ETA: 0s - loss: 0.4756 - accuracy: 0.7493

150/231 [==================>...........] - ETA: 0s - loss: 0.4742 - accuracy: 0.7496

159/231 [===================>..........] - ETA: 0s - loss: 0.4766 - accuracy: 0.7480

167/231 [====================>.........] - ETA: 0s - loss: 0.4760 - accuracy: 0.7474

175/231 [=====================>........] - ETA: 0s - loss: 0.4765 - accuracy: 0.7491

184/231 [======================>.......] - ETA: 0s - loss: 0.4795 - accuracy: 0.7473

193/231 [========================>.....] - ETA: 0s - loss: 0.4785 - accuracy: 0.7479

201/231 [=========================>....] - ETA: 0s - loss: 0.4769 - accuracy: 0.7486

209/231 [==========================>...] - ETA: 0s - loss: 0.4763 - accuracy: 0.7482

217/231 [===========================>..] - ETA: 0s - loss: 0.4753 - accuracy: 0.7483

225/231 [============================>.] - ETA: 0s - loss: 0.4740 - accuracy: 0.7501

231/231 [==============================] - 2s 8ms/step - loss: 0.4749 - accuracy: 0.7492 - val_loss: 0.4838 - val_accuracy: 0.7503


Epoch 10/10
  1/231 [..............................] - ETA: 0s - loss: 0.3779 - accuracy: 0.8125

 10/231 [>.............................] - ETA: 1s - loss: 0.4530 - accuracy: 0.7750

 19/231 [=>............................] - ETA: 1s - loss: 0.4701 - accuracy: 0.7582

 28/231 [==>...........................] - ETA: 1s - loss: 0.4545 - accuracy: 0.7589

 37/231 [===>..........................] - ETA: 1s - loss: 0.4526 - accuracy: 0.7627

 45/231 [====>.........................] - ETA: 1s - loss: 0.4480 - accuracy: 0.7681

 53/231 [=====>........................] - ETA: 1s - loss: 0.4539 - accuracy: 0.7636

 62/231 [=======>......................] - ETA: 1s - loss: 0.4560 - accuracy: 0.7661

 70/231 [========>.....................] - ETA: 0s - loss: 0.4510 - accuracy: 0.7652

 79/231 [=========>....................] - ETA: 0s - loss: 0.4562 - accuracy: 0.7654

 87/231 [==========>...................] - ETA: 0s - loss: 0.4641 - accuracy: 0.7604

 95/231 [===========>..................] - ETA: 0s - loss: 0.4653 - accuracy: 0.7618

103/231 [============>.................] - ETA: 0s - loss: 0.4655 - accuracy: 0.7621

112/231 [=============>................] - ETA: 0s - loss: 0.4644 - accuracy: 0.7631

121/231 [==============>...............] - ETA: 0s - loss: 0.4628 - accuracy: 0.7642

130/231 [===============>..............] - ETA: 0s - loss: 0.4688 - accuracy: 0.7582

138/231 [================>.............] - ETA: 0s - loss: 0.4697 - accuracy: 0.7563

147/231 [==================>...........] - ETA: 0s - loss: 0.4689 - accuracy: 0.7540

156/231 [===================>..........] - ETA: 0s - loss: 0.4663 - accuracy: 0.7550

165/231 [====================>.........] - ETA: 0s - loss: 0.4685 - accuracy: 0.7527

174/231 [=====================>........] - ETA: 0s - loss: 0.4665 - accuracy: 0.7523

182/231 [======================>.......] - ETA: 0s - loss: 0.4666 - accuracy: 0.7538

191/231 [=======================>......] - ETA: 0s - loss: 0.4653 - accuracy: 0.7552

200/231 [========================>.....] - ETA: 0s - loss: 0.4670 - accuracy: 0.7536

209/231 [==========================>...] - ETA: 0s - loss: 0.4672 - accuracy: 0.7521

217/231 [===========================>..] - ETA: 0s - loss: 0.4679 - accuracy: 0.7513

226/231 [============================>.] - ETA: 0s - loss: 0.4667 - accuracy: 0.7518

231/231 [==============================] - 2s 7ms/step - loss: 0.4673 - accuracy: 0.7502 - val_loss: 0.4847 - val_accuracy: 0.7486


In [27]:
loss, accuracy = model.evaluate(test_ds)
print("Accuracy", accuracy)

 1/73 [..............................] - ETA: 0s - loss: 0.8083 - accuracy: 0.5625

12/73 [===>..........................] - ETA: 0s - loss: 0.5462 - accuracy: 0.7370

22/73 [========>.....................] - ETA: 0s - loss: 0.5326 - accuracy: 0.7372

32/73 [============>.................] - ETA: 0s - loss: 0.5330 - accuracy: 0.7344

43/73 [================>.............] - ETA: 0s - loss: 0.5237 - accuracy: 0.7318

53/73 [====================>.........] - ETA: 0s - loss: 0.5193 - accuracy: 0.7364

64/73 [=========================>....] - ETA: 0s - loss: 0.5216 - accuracy: 0.7373

73/73 [==============================] - 0s 5ms/step - loss: 0.5179 - accuracy: 0.7413


Accuracy 0.7413344979286194


Key point: You will typically see best results with deep learning with much larger and more complex datasets. When working with a small dataset like this one, we recommend using a decision tree or random forest as a strong baseline. The goal of this tutorial is not to train an accurate model, but to demonstrate the mechanics of working with structured data, so you have code to use as a starting point when working with your own datasets in the future.

## Next steps
The best way to learn more about classifying structured data is to try it yourself. We suggest finding another dataset to work with, and training a model to classify it using code similar to the above. To improve accuracy, think carefully about which features to include in your model, and how they should be represented.